const fieldWeights = {
    "name": 10,
    "version": 1,
    "organization": 5,
    "description": 10,
    "permissions.licenses.URL": 1,
    "permissions.licenses.name": 7,
    "permissions.usageType": 10,
    "permissions.exemptionText": 5,
    "tags": 10,
    "contact.email": 10,
    "contact.name": 5,
    "contact.URL": 5,
    "contact.phone": 5,
    "status": 5,
    "vcs": 5,
    "repositoryURL": 10,
    "homepageURL": 7,
    "downloadURL": 3,
    "disclaimerURL": 3,
    "disclaimerText": 3,
    "languages": 10,
    "laborHours": 10,
    "relatedCode.name": 1,
    "relatedCode.URL": 1,
    "relatedCode.isGovernmentRepo": 1,
    "reusedCode.name": 1,
    "reusedCode.URL": 1,
    "partners.name": 1,
    "partners.email": 1,
    "date.created": 5,
    "date.lastModified": 5,
    "date.metadataLastUpdated": 2
};

module.exports = fieldWeights;