const fieldWeights = {
    "name": 1,
    "description": 1,
    "permissions.licenses": 1,
    "permissions.licenses.URL": 1,
    "permissions.licenses.name": 1,
    "permissions.usageType.openSource": 1,
    "permissions.usageType.governmentWideReuse": 0.5,
    "permissions.usageType.exempt": 0.1,
    "permissions.exemptionText": 0.1,
    "organization": 1,
    "contact.email": 1,
    "contact.name": 1,
    "contact.URL": 1,
    "contact.phone": 1,
    "tags": 1,
    "laborHours": 1,
    "languages": 0.8,
    "repositoryURL": 0.8,
    "homepageURL": 0.8,
    "downloadURL": 0.8,
    "vcs": 0.8,
    "date.created": 0.6,
    "date.lastModified": 0.6,
    "date.metadataLastUpdated": 0.6,
    "version": 0.6,
    "status": 0.6,
    "disclaimerURL": 0.4,
    "disclaimerText": 0.4,
    "relatedCode.name": 0.4,
    "relatedCode.URL": 0.4,
    "reusedCode.name": 0.4,
    "reusedCode.URL": 0.4,
    "partners.name": 0.4,
    "partners.email": 0.4,
    "target_operating_systems": 0.2,
    "additional_information": 0.1
};

module.exports = fieldWeights;