version: '2.4'
services:
  harvester:
    build: .
    image: 'codegov/code-gov-harvester:latest'
    container_name: 'code-gov-harvester'
    env_file:
      - ./.env
    depends_on:
      - elasticsearch
    volumes:
      - .:/usr/src/app
    command: ["npm", "start"]
    networks:
    - esnet

  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:5.6.9"
    environment:
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
      - "9300:9300"
    container_name: 'code-gov-data'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
    - esnet

networks:
  esnet:
    driver: bridge
