FROM node:dubnium-slim

ARG NODE_ENV
ENV NODE_ENV=${NODE_ENV}

ARG ELASTICSEARCH_SERVICE_NAME
ENV ELASTICSEARCH_SERVICE_NAME=${ELASTICSEARCH_SERVICE_NAME}

ARG LOGGER_LEVEL
ENV LOGGER_LEVEL=${LOGGER_LEVEL}

ARG GET_REMOTE_METADATA
ENV GET_REMOTE_METADATA=${GET_REMOTE_METADATA}

ARG GET_GITHUB_DATA
ENV GET_GITHUB_DATA=${GET_GITHUB_DATA}

ARG REMOTE_METADATA_LOCATION
ENV REMOTE_METADATA_LOCATION=${REMOTE_METADATA_LOCATION}

ARG GITHUB_API_KEY
ENV GITHUB_API_KEY=${GITHUB_API_KEY}

ARG ES_URI
ENV ES_URI=${ES_URI}

WORKDIR /usr/src/app
VOLUME "/usr/src/app"

COPY package*.json ./

RUN npm install

CMD [ "npm", "start" ]
